In [104]:
from sklearn.datasets import load_iris

In [105]:
iris = load_iris()

In [106]:
X = iris['data']

In [107]:
y = iris['target']

In [108]:
from sklearn.cross_validation import train_test_split

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [110]:
import numpy as np
X_train = np.array( X_train, dtype=np.float32 ) 
X_test = np.array( X_test, dtype=np.float32 )

In [111]:
from tensorflow.contrib.learn.python import learn

In [112]:
feature_columns = learn.infer_real_valued_columns_from_input(X_train)

In [113]:
classifier = learn.DNNClassifier(hidden_units=[10,20,10], n_classes=3, feature_columns=feature_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_id': 0, '_environment': 'local', '_tf_random_seed': None, '_save_summary_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_num_ps_replicas': 0, '_evaluation_master': '', '_save_checkpoints_steps': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_keep_checkpoint_max': 5, '_save_checkpoints_secs': 600, '_task_type': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x117b7ff98>, '_session_config': None, '_model_dir': '/var/folders/3k/1jc3h_hx5j18ys7h3v3mxzw80000gn/T/tmp5x_qw3wm', '_num_worker_replicas': 0, '_is_chief': True, '_master': ''}


In [114]:
import tensorflow as tf 
def get_train_inputs():
    x = tf.constant(X_train)
    y = tf.constant(y_train)

    return x, y

classifier.fit(input_fn=get_train_inputs, steps=200)

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/3k/1jc3h_hx5j18ys7h3v3mxzw80000gn/T/tmp5x_qw3wm/model.ckpt.
INFO:tensorflow:loss = 1.86435, step = 1
INFO:tensorflow:global_step/sec: 731.219
INFO:tensorflow:loss = 0.222981, step = 101 (0.139 sec)
INFO:tensorflow:Saving checkpoints for 200 into /var/folders/3k/1jc3h_hx5j18ys7h3v3mxzw80000gn/T/tmp5x_qw3wm/model.ckpt.
INFO:tensorflow:Loss for final step: 0.11495.


DNNClassifier(params={'input_layer_min_slice_size': None, 'gradient_clip_norm': None, 'feature_columns': (_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float32, normalizer=None),), 'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x1156ff438>, 'dropout': None, 'embedding_lr_multipliers': None, 'optimizer': None, 'hidden_units': [10, 20, 10], 'activation_fn': <function relu at 0x11142e9d8>})

In [115]:
def get_test_inputs():
    x = tf.constant(X_test)
    return x 

iris_predictions = list(classifier.predict_classes (input_fn=get_test_inputs))


INFO:tensorflow:Restoring parameters from /var/folders/3k/1jc3h_hx5j18ys7h3v3mxzw80000gn/T/tmp5x_qw3wm/model.ckpt-200


In [116]:
from sklearn.metrics import classification_report, confusion_matrix

In [117]:
print(classification_report(y_test,  iris_predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      0.95      0.97        20
          2       0.94      1.00      0.97        16

avg / total       0.98      0.98      0.98        45



In [103]:
print(confusion_matrix(y_test,  iris_predictions))

[[14  0  0]
 [ 0 14  1]
 [ 0  0 16]]
